// Otavio Luiz Gonzaga - RA: a2648920

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */

/**
 *
 * @author otavio
 */
public class FitoterapicoFormulario extends javax.swing.JPanel implements FormularioComponente<Fitoterapico> {

    /**
     * Creates new form FitoterapicoFormulario
     */
    public FitoterapicoFormulario() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated
    // Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        plataOrigemLabel = new javax.swing.JLabel();
        plantaOrigemInput = new javax.swing.JTextField();
        exigeRegistroAnvisaLabel = new javax.swing.JLabel();
        exigeRegistroAnvisaCheckbox = new javax.swing.JCheckBox();

        plataOrigemLabel.setText("Planta de origem");

        exigeRegistroAnvisaLabel.setText("Exige registro da ANVISA?");

        exigeRegistroAnvisaCheckbox.setText("Sim, exige");
        exigeRegistroAnvisaCheckbox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exigeRegistroAnvisaCheckboxActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(plataOrigemLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 256,
                                                Short.MAX_VALUE)
                                        .addComponent(plantaOrigemInput))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(exigeRegistroAnvisaLabel)
                                        .addComponent(exigeRegistroAnvisaCheckbox))
                                .addGap(0, 53, Short.MAX_VALUE)));
        layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(plataOrigemLabel)
                                        .addComponent(exigeRegistroAnvisaLabel))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(plantaOrigemInput, javax.swing.GroupLayout.PREFERRED_SIZE,
                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(exigeRegistroAnvisaCheckbox))));
    }// </editor-fold>//GEN-END:initComponents

    private void exigeRegistroAnvisaCheckboxActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_exigeRegistroAnvisaCheckboxActionPerformed
        // TODO add your handling code here:
    }// GEN-LAST:event_exigeRegistroAnvisaCheckboxActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox exigeRegistroAnvisaCheckbox;
    private javax.swing.JLabel exigeRegistroAnvisaLabel;
    private javax.swing.JTextField plantaOrigemInput;
    private javax.swing.JLabel plataOrigemLabel;
    // End of variables declaration//GEN-END:variables

    @Override
    public void limparFormulario() {
        this.exigeRegistroAnvisaCheckbox.setSelected(false);
        this.exigeRegistroAnvisaCheckbox.repaint();
        this.exigeRegistroAnvisaCheckbox.revalidate();

        this.plantaOrigemInput.setText("");
        this.plantaOrigemInput.repaint();
        this.plantaOrigemInput.revalidate();

        this.repaint();
        this.revalidate();
    }

    @Override
    public void setarDados(Fitoterapico medicamento) throws IllegalArgumentException {
        String plantaOrigem = this.plantaOrigemInput.getText();
        boolean exigeRegistroAnvisa = this.exigeRegistroAnvisaCheckbox.isSelected();

        if (plantaOrigem.isBlank()) {
            throw new IllegalArgumentException("Preencha o campo \"Planta de origem\"");
        }

        medicamento.setExigeRegistroAnvisa(exigeRegistroAnvisa);
        medicamento.setPlantaOrigem(plantaOrigem);
    }

    @Override
    public void preencherForm(Fitoterapico medicamento) {
        this.plantaOrigemInput.setText(medicamento.getPlantaOrigem());
        this.exigeRegistroAnvisaCheckbox.setSelected(medicamento.getExigeRegistroAnvisa());
        
        this.repaint();
        this.revalidate();
    }
}
