// Otavio Luiz Gonzaga - RA: a2648920

import javax.swing.JOptionPane;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
/**
 *
 * @author otavio
 */
public class FormCalcDosagem extends javax.swing.JFrame {

    private Medicamento medicamento;

    public Medicamento getMedicamento() {
        return medicamento;
    }

    public void setMedicamento(Medicamento medicamento) {
        this.medicamento = medicamento;

        this.nomeLabel.setText(medicamento.getNome());
        this.dosagemPadraoLabel.setText(Float.toString(medicamento.getDosagemMg()));
    }

    private static FormCalcDosagem instance;
    private static final java.util.logging.Logger logger = java.util.logging.Logger
            .getLogger(FormCalcDosagem.class.getName());

    /**
     * Creates new form FormCalcDosagem
     */
    private FormCalcDosagem() {
        initComponents();
    }

    public static FormCalcDosagem getInstance() {
        if (instance == null) {
            instance = new FormCalcDosagem();
        }

        return instance;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated
    // Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        tituloLabel = new javax.swing.JLabel();
        instrucoesLabel = new javax.swing.JLabel();
        pesoLabel = new javax.swing.JLabel();
        dosagemLabel = new javax.swing.JLabel();
        pesoInput = new javax.swing.JTextField();
        dosagemInput = new javax.swing.JTextField();
        dosagemSubLabel = new javax.swing.JLabel();
        calcularBotao = new javax.swing.JButton();
        cancelarBotao = new javax.swing.JButton();
        medicamentoLabel = new javax.swing.JLabel();
        dosagemIndicadorPadraoLabel = new javax.swing.JLabel();
        dosagemPadraoLabel = new javax.swing.JLabel();
        nomeLabel = new javax.swing.JLabel();
        resultadoIndicadorLabel = new javax.swing.JLabel();
        resultadoLabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        tituloLabel.setFont(new java.awt.Font("sansserif", 0, 24)); // NOI18N
        tituloLabel.setText("Calculadora de dosagem");

        instrucoesLabel.setFont(new java.awt.Font("sansserif", 0, 14)); // NOI18N
        instrucoesLabel.setForeground(new java.awt.Color(102, 102, 102));
        instrucoesLabel.setText("Preencha os campos para calcular a dosagem");

        pesoLabel.setText("Peso");

        dosagemLabel.setText("Dosagem");

        pesoInput.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pesoInputActionPerformed(evt);
            }
        });

        dosagemInput.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dosagemInputActionPerformed(evt);
            }
        });

        dosagemSubLabel.setFont(new java.awt.Font("sansserif", 0, 12)); // NOI18N
        dosagemSubLabel.setForeground(new java.awt.Color(102, 102, 102));
        dosagemSubLabel.setText("Deixe em branco para a dosagem padrão");

        calcularBotao.setText("Calcular");
        calcularBotao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                calcularBotaoActionPerformed(evt);
            }
        });

        cancelarBotao.setText("Cancelar");
        cancelarBotao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelarBotaoActionPerformed(evt);
            }
        });

        medicamentoLabel.setText("Medicamento: ");

        dosagemIndicadorPadraoLabel.setText("Dosagem padrão:");

        dosagemPadraoLabel.setText("0");

        nomeLabel.setText("nome");

        resultadoIndicadorLabel.setFont(new java.awt.Font("sansserif", 1, 18)); // NOI18N
        resultadoIndicadorLabel.setText("Resultado:");

        resultadoLabel.setFont(new java.awt.Font("sansserif", 1, 18)); // NOI18N
        resultadoLabel.setText("0");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout
                                                .createSequentialGroup()
                                                .addGap(0, 0, Short.MAX_VALUE)
                                                .addGroup(layout
                                                        .createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout
                                                                .createSequentialGroup()
                                                                .addPreferredGap(
                                                                        javax.swing.LayoutStyle.ComponentPlacement.RELATED,
                                                                        306, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                .addComponent(cancelarBotao)
                                                                .addPreferredGap(
                                                                        javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                                .addComponent(calcularBotao))
                                                        .addGroup(layout.createSequentialGroup()
                                                                .addGroup(layout.createParallelGroup(
                                                                        javax.swing.GroupLayout.Alignment.LEADING,
                                                                        false)
                                                                        .addComponent(pesoLabel,
                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                Short.MAX_VALUE)
                                                                        .addComponent(pesoInput,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                256,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE))
                                                                .addGap(18, 18, 18)
                                                                .addGroup(layout.createParallelGroup(
                                                                        javax.swing.GroupLayout.Alignment.LEADING)
                                                                        .addComponent(resultadoLabel)
                                                                        .addGroup(layout.createParallelGroup(
                                                                                javax.swing.GroupLayout.Alignment.LEADING,
                                                                                false)
                                                                                .addComponent(resultadoIndicadorLabel,
                                                                                        javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                        javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                        Short.MAX_VALUE)
                                                                                .addComponent(dosagemSubLabel,
                                                                                        javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                        256, Short.MAX_VALUE)
                                                                                .addComponent(dosagemInput)
                                                                                .addComponent(dosagemLabel,
                                                                                        javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                        javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                        Short.MAX_VALUE))))))
                                        .addGroup(layout.createSequentialGroup()
                                                .addGroup(layout
                                                        .createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addComponent(tituloLabel)
                                                        .addComponent(instrucoesLabel)
                                                        .addGroup(layout.createSequentialGroup()
                                                                .addGroup(layout.createParallelGroup(
                                                                        javax.swing.GroupLayout.Alignment.LEADING)
                                                                        .addComponent(dosagemIndicadorPadraoLabel)
                                                                        .addComponent(medicamentoLabel))
                                                                .addPreferredGap(
                                                                        javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                                .addGroup(layout.createParallelGroup(
                                                                        javax.swing.GroupLayout.Alignment.LEADING)
                                                                        .addComponent(nomeLabel)
                                                                        .addComponent(dosagemPadraoLabel))))
                                                .addGap(0, 0, Short.MAX_VALUE)))
                                .addContainerGap()));
        layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(tituloLabel)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(instrucoesLabel)
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(medicamentoLabel)
                                        .addComponent(nomeLabel)
                                        .addComponent(resultadoIndicadorLabel))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                .addComponent(dosagemIndicadorPadraoLabel)
                                                .addComponent(dosagemPadraoLabel))
                                        .addComponent(resultadoLabel))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 19,
                                        Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(pesoLabel)
                                        .addComponent(dosagemLabel))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(pesoInput, javax.swing.GroupLayout.PREFERRED_SIZE,
                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(dosagemInput, javax.swing.GroupLayout.PREFERRED_SIZE,
                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(dosagemSubLabel)
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(calcularBotao)
                                        .addComponent(cancelarBotao))
                                .addContainerGap()));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void dosagemInputActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_dosagemInputActionPerformed
        // TODO add your handling code here:
    }// GEN-LAST:event_dosagemInputActionPerformed

    private void pesoInputActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_pesoInputActionPerformed
        // TODO add your handling code here:
    }// GEN-LAST:event_pesoInputActionPerformed

    private void calcularBotaoActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_calcularBotaoActionPerformed
        try {
            float peso = Float.parseFloat(this.pesoInput.getText());

            float result = this.dosagemInput.getText().isBlank()
                    ? medicamento.calcDosagem(peso)
                    : Medicamento.calcDosagem(peso, Float.parseFloat(this.dosagemInput.getText()));

            this.resultadoLabel.setText(Float.toString(result));
        } catch (NumberFormatException nfe) {
            JOptionPane.showMessageDialog(
                    this,
                    "Os valores informados precisam ser números",
                    "Erro",
                    JOptionPane.ERROR_MESSAGE);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(
                    this,
                    e.getMessage(),
                    "Erro " + e.getClass().getName(),
                    JOptionPane.ERROR_MESSAGE);
        }

    }// GEN-LAST:event_calcularBotaoActionPerformed

    private void cancelarBotaoActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_cancelarBotaoActionPerformed
        this.dispose();
    }// GEN-LAST:event_cancelarBotaoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        // <editor-fold defaultstate="collapsed" desc=" Look and feel setting code
        // (optional) ">
        /*
         * If Nimbus (introduced in Java SE 6) is not available, stay with the default
         * look and feel.
         * For details see
         * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        // </editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new FormCalcDosagem().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton calcularBotao;
    private javax.swing.JButton cancelarBotao;
    private javax.swing.JLabel dosagemIndicadorPadraoLabel;
    private javax.swing.JTextField dosagemInput;
    private javax.swing.JLabel dosagemLabel;
    private javax.swing.JLabel dosagemPadraoLabel;
    private javax.swing.JLabel dosagemSubLabel;
    private javax.swing.JLabel instrucoesLabel;
    private javax.swing.JLabel medicamentoLabel;
    private javax.swing.JLabel nomeLabel;
    private javax.swing.JTextField pesoInput;
    private javax.swing.JLabel pesoLabel;
    private javax.swing.JLabel resultadoIndicadorLabel;
    private javax.swing.JLabel resultadoLabel;
    private javax.swing.JLabel tituloLabel;
    // End of variables declaration//GEN-END:variables
}
