// Otavio Luiz Gonzaga - RA: a2648920

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
/**
 *
 * @author otavio
 */
public class FormGenerico extends javax.swing.JPanel implements FormularioComponente<Generico> {

    /**
     * Creates new form GenericoFormulario
     */
    public FormGenerico() {
        initComponents();
        carregarLaboratorios();
    }

    private void carregarLaboratorios() {
        laboratorioSelect.removeAllItems();

        for (Laboratorio l : BDLaboratorio.getInstance().getLaboratorios()) {
            laboratorioSelect.addItem(l);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        comumFormulario = new FormComum();
        nomeGenericoLabel = new javax.swing.JLabel();
        nomeGenericoInput = new javax.swing.JTextField();
        nomeComercialLabel = new javax.swing.JLabel();
        nomeComercialInput = new javax.swing.JTextField();
        laboratorioLabel = new javax.swing.JLabel();
        laboratorioSelect = new javax.swing.JComboBox<>();

        nomeGenericoLabel.setText("Nome genérico");

        nomeGenericoInput.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nomeGenericoInputActionPerformed(evt);
            }
        });

        nomeComercialLabel.setText("Nome comercial");

        laboratorioLabel.setText("Laboratório");

        laboratorioSelect.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                laboratorioSelectActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(nomeGenericoInput, javax.swing.GroupLayout.PREFERRED_SIZE, 256, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(nomeComercialInput))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(nomeGenericoLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 256, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(nomeComercialLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 256, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(comumFormulario, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
            .addGroup(layout.createSequentialGroup()
                .addComponent(laboratorioLabel)
                .addGap(0, 0, Short.MAX_VALUE))
            .addComponent(laboratorioSelect, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(comumFormulario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nomeGenericoLabel)
                    .addComponent(nomeComercialLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nomeGenericoInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(nomeComercialInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(laboratorioLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(laboratorioSelect, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void laboratorioSelectActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_laboratorioSelectActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_laboratorioSelectActionPerformed

    private void nomeGenericoInputActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_nomeGenericoInputActionPerformed
        // TODO add your handling code here:
    }// GEN-LAST:event_nomeGenericoInputActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private FormComum comumFormulario;
    private javax.swing.JLabel laboratorioLabel;
    private javax.swing.JComboBox<Laboratorio> laboratorioSelect;
    private javax.swing.JTextField nomeComercialInput;
    private javax.swing.JLabel nomeComercialLabel;
    private javax.swing.JTextField nomeGenericoInput;
    private javax.swing.JLabel nomeGenericoLabel;
    // End of variables declaration//GEN-END:variables

    @Override
    public void limparFormulario() {
        this.nomeComercialInput.setText("");
        this.nomeComercialInput.repaint();
        this.nomeComercialInput.revalidate();

        this.nomeGenericoInput.setText("");
        this.nomeGenericoInput.repaint();
        this.nomeGenericoInput.revalidate();

        this.comumFormulario.limparFormulario();
        this.repaint();
        this.revalidate();
    }

    @Override
    public void setarDados(Generico medicamento) throws IllegalArgumentException {
        this.comumFormulario.setarDados(medicamento);

        String nomeComercial = this.nomeComercialInput.getText();
        String nomeGenerico = this.nomeGenericoInput.getText();
        Laboratorio laboratorioOriginal = (Laboratorio) this.laboratorioSelect.getSelectedItem();

        if (nomeComercial.isBlank()) {
            throw new IllegalArgumentException("Preencha o campo \"Nome comercial\"");
        }
        if (nomeGenerico.isBlank()) {
            throw new IllegalArgumentException("Preencha o campo \"Nome genérico\"");
        }

        medicamento.setNomeComercial(nomeComercial);
        medicamento.setNomeGenerico(nomeGenerico);
        medicamento.setLaboratorioOriginal(laboratorioOriginal);
    }
}
