// Otavio Luiz Gonzaga - RA: a2648920

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */

/**
 *
 * @author otavio
 */
public class FormControlado extends javax.swing.JPanel implements FormularioComponente<Controlado> {

    /**
     * Creates new form ControladoFormulario
     */
    public FormControlado() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        tipoReceitaLabel = new javax.swing.JLabel();
        tipoReceitaInput = new javax.swing.JTextField();
        necessitaRetencaoReceitaLabel = new javax.swing.JLabel();
        necessitaRetencaoReceitaCheckbox = new javax.swing.JCheckBox();

        tipoReceitaLabel.setText("Tipo de receita");

        necessitaRetencaoReceitaLabel.setText("Necessita retenção de receita?");

        necessitaRetencaoReceitaCheckbox.setText("Sim, necessita");
        necessitaRetencaoReceitaCheckbox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                necessitaRetencaoReceitaCheckboxActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(tipoReceitaLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 256, Short.MAX_VALUE)
                    .addComponent(tipoReceitaInput))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(necessitaRetencaoReceitaLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 256, Short.MAX_VALUE)
                    .addComponent(necessitaRetencaoReceitaCheckbox, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tipoReceitaLabel)
                    .addComponent(necessitaRetencaoReceitaLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tipoReceitaInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(necessitaRetencaoReceitaCheckbox)))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void necessitaRetencaoReceitaCheckboxActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_necessitaRetencaoReceitaCheckboxActionPerformed
        // TODO add your handling code here:
    }// GEN-LAST:event_necessitaRetencaoReceitaCheckboxActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox necessitaRetencaoReceitaCheckbox;
    private javax.swing.JLabel necessitaRetencaoReceitaLabel;
    private javax.swing.JTextField tipoReceitaInput;
    private javax.swing.JLabel tipoReceitaLabel;
    // End of variables declaration//GEN-END:variables

    @Override
    public void limparFormulario() {
        this.necessitaRetencaoReceitaCheckbox.setSelected(false);
        this.necessitaRetencaoReceitaCheckbox.repaint();
        this.necessitaRetencaoReceitaCheckbox.revalidate();

        this.tipoReceitaInput.setText("");
        this.tipoReceitaInput.repaint();
        this.tipoReceitaInput.revalidate();

        this.repaint();
        this.revalidate();
    }

    @Override
    public void setarDados(Controlado medicamento) throws IllegalArgumentException {
        String tipoReceita = this.tipoReceitaInput.getText();
        boolean necessitaRetencaoReceita = this.necessitaRetencaoReceitaCheckbox.isSelected();

        if (tipoReceita.isBlank()) {
            throw new IllegalArgumentException("Preencha o campo \"Tipo de receita\"");
        }

        medicamento.setTipoReceita(tipoReceita);
        medicamento.setNecessitaRetencaoReceita(necessitaRetencaoReceita);
    }
}
