// Otavio Luiz Gonzaga - RA: a2648920

import java.awt.CardLayout;
import javax.swing.JOptionPane;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
/**
 *
 * @author otavio
 */
public class FormMedicamento extends javax.swing.JFrame implements FormularioComponente<Medicamento> {

    FormComum comumPanel;
    FormGenerico genericoPanel;
    FormControlado controladoPanel;
    FitoterapicoFormulario fitoterapicoPanel;

    private static FormMedicamento instance;
    private static final java.util.logging.Logger logger = java.util.logging.Logger
            .getLogger(FormMedicamento.class.getName());

    /**
     * Creates new form Formulario
     */
    private FormMedicamento() {
        this.comumPanel = new FormComum();
        this.genericoPanel = new FormGenerico();
        this.controladoPanel = new FormControlado();
        this.fitoterapicoPanel = new FitoterapicoFormulario();

        initComponents();
        limparFormulario();

        painelCamposEspecificos.setLayout(new CardLayout());
        painelCamposEspecificos.add(comumPanel, "Comum");
        painelCamposEspecificos.add(genericoPanel, "Genérico");
        painelCamposEspecificos.add(controladoPanel, "Controlado");
        painelCamposEspecificos.add(fitoterapicoPanel, "Fitoterápico");

        generoSelect.addActionListener((java.awt.event.ActionEvent e) -> {
            String tipo = (String) generoSelect.getSelectedItem();
            CardLayout cl = (CardLayout) painelCamposEspecificos.getLayout();
            cl.show(painelCamposEspecificos, tipo);
        });
    }

    public static FormMedicamento getInstance() {
        if (instance == null) {
            instance = new FormMedicamento();
        }

        return instance;
    }

    @Override
    public void setVisible(boolean b) {
        limparFormulario();
        super.setVisible(b);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jFormattedTextField1 = new javax.swing.JFormattedTextField();
        nomeLabel = new javax.swing.JLabel();
        nomeInput = new javax.swing.JTextField();
        precoLabel = new javax.swing.JLabel();
        precoInput = new javax.swing.JTextField();
        pricipioAtivoLabel = new javax.swing.JLabel();
        principioAtivoInput = new javax.swing.JTextField();
        dosagemLabel = new javax.swing.JLabel();
        dosagemInput = new javax.swing.JTextField();
        generoLabel = new javax.swing.JLabel();
        generoSelect = new javax.swing.JComboBox<>();
        painelCamposEspecificos = new javax.swing.JPanel();
        salvarBotao = new javax.swing.JButton();
        cancelarBotao = new javax.swing.JButton();
        resetarBotao = new javax.swing.JButton();

        jFormattedTextField1.setText("jFormattedTextField1");

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        nomeLabel.setText("Nome");

        nomeInput.setToolTipText("");
        nomeInput.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nomeInputActionPerformed(evt);
            }
        });

        precoLabel.setText("Preço");

        precoInput.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                precoInputActionPerformed(evt);
            }
        });

        pricipioAtivoLabel.setText("Principio Ativo");

        principioAtivoInput.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                principioAtivoInputActionPerformed(evt);
            }
        });

        dosagemLabel.setText("Dosagem");

        dosagemInput.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dosagemInputActionPerformed(evt);
            }
        });

        generoLabel.setText("Gênero");

        generoSelect.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Comum", "Genérico", "Controlado", "Fitoterápico" }));
        generoSelect.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                generoSelectActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout painelCamposEspecificosLayout = new javax.swing.GroupLayout(painelCamposEspecificos);
        painelCamposEspecificos.setLayout(painelCamposEspecificosLayout);
        painelCamposEspecificosLayout.setHorizontalGroup(
            painelCamposEspecificosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 530, Short.MAX_VALUE)
        );
        painelCamposEspecificosLayout.setVerticalGroup(
            painelCamposEspecificosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 222, Short.MAX_VALUE)
        );

        salvarBotao.setText("Salvar");
        salvarBotao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                salvarBotaoActionPerformed(evt);
            }
        });

        cancelarBotao.setText("Cancelar");
        cancelarBotao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelarBotaoActionPerformed(evt);
            }
        });

        resetarBotao.setText("Resetar");
        resetarBotao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                resetarBotaoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(resetarBotao)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(cancelarBotao)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(salvarBotao))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(generoSelect, javax.swing.GroupLayout.PREFERRED_SIZE, 530, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(generoLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 530, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(painelCamposEspecificos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(principioAtivoInput)
                                    .addComponent(nomeInput)
                                    .addComponent(nomeLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(pricipioAtivoLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 256, Short.MAX_VALUE))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(precoInput)
                                    .addComponent(precoLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(dosagemInput)
                                    .addComponent(dosagemLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))))
                .addGap(20, 20, 20))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nomeLabel)
                    .addComponent(precoLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nomeInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(precoInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(pricipioAtivoLabel)
                    .addComponent(dosagemLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(principioAtivoInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(dosagemInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(generoLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(generoSelect, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(painelCamposEspecificos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(salvarBotao)
                    .addComponent(cancelarBotao)
                    .addComponent(resetarBotao))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void nomeInputActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_nomeInputActionPerformed
        // TODO add your handling code here:
    }// GEN-LAST:event_nomeInputActionPerformed

    private void principioAtivoInputActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_principioAtivoInputActionPerformed
        // TODO add your handling code here:
    }// GEN-LAST:event_principioAtivoInputActionPerformed

    private void generoSelectActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_generoSelectActionPerformed

    }// GEN-LAST:event_generoSelectActionPerformed

    private void precoInputActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_precoInputActionPerformed
        // TODO add your handling code here:
    }// GEN-LAST:event_precoInputActionPerformed

    private void dosagemInputActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_dosagemInputActionPerformed
        // TODO add your handling code here:
    }// GEN-LAST:event_dosagemInputActionPerformed

    private void salvarBotaoActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_salvarBotaoActionPerformed
        Medicamento medicamento = null;

        try {
            switch ((String) this.generoSelect.getSelectedItem()) {
                case "Comum" -> {
                    medicamento = new Comum();
                    this.comumPanel.setarDados((Comum) medicamento);
                }
                case "Genérico" -> {
                    medicamento = new Generico();
                    this.genericoPanel.setarDados((Generico) medicamento);
                }
                case "Controlado" -> {
                    medicamento = new Controlado();
                    this.controladoPanel.setarDados((Controlado) medicamento);
                }
                case "Fitoterápico" -> {
                    medicamento = new Fitoterapico();
                    this.fitoterapicoPanel.setarDados((Fitoterapico) medicamento);
                }
                default ->
                    throw new AssertionError();
            }

            this.setarDados(medicamento);

            this.limparFormulario();
            this.dispose();
            BDMedicamento.getInstance().addMedicamento(medicamento);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(
                    this,
                    e.getMessage(),
                    "Erro " + e.getClass().getName(),
                    JOptionPane.ERROR_MESSAGE);
        }
    }// GEN-LAST:event_salvarBotaoActionPerformed

    private void cancelarBotaoActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_cancelarBotaoActionPerformed
        this.limparFormulario();
        this.dispose();
    }// GEN-LAST:event_cancelarBotaoActionPerformed

    private void resetarBotaoActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_resetarBotaoActionPerformed
        this.limparFormulario();
    }// GEN-LAST:event_resetarBotaoActionPerformed

    @Override
    public final void limparFormulario() {
        nomeInput.setText("");
        nomeInput.repaint();
        nomeInput.revalidate();

        precoInput.setText("");
        precoInput.repaint();
        precoInput.revalidate();

        principioAtivoInput.setText("");
        principioAtivoInput.repaint();
        principioAtivoInput.revalidate();

        dosagemInput.setText("");
        dosagemInput.repaint();
        dosagemInput.revalidate();

        generoSelect.setSelectedIndex(0);
        generoSelect.repaint();
        generoSelect.revalidate();

        FormularioComponente[] subFormularios = new FormularioComponente[] {
                comumPanel, genericoPanel, controladoPanel, fitoterapicoPanel
        };

        for (FormularioComponente subFormulario : subFormularios) {
            subFormulario.limparFormulario();
        }
        this.repaint();
        this.revalidate();
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        // <editor-fold defaultstate="collapsed" desc=" Look and feel setting code
        // (optional) ">
        /*
         * If Nimbus (introduced in Java SE 6) is not available, stay with the default
         * look and feel.
         * For details see
         * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        // </editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new FormMedicamento().setVisible(true));
    }

    @Override
    public void setarDados(Medicamento medicamento)
            throws NumeroNegativoException, NumberFormatException, IllegalArgumentException {
        String dosagemMg = this.dosagemInput.getText();
        String nome = this.nomeInput.getText();
        String preco = this.precoInput.getText();
        String principioAtivo = this.principioAtivoInput.getText();

        if (nome.isBlank()) {
            throw new IllegalArgumentException("Preencha o campo \"Nome\"");
        }

        if (preco.isBlank()) {
            throw new IllegalArgumentException("Preencha o campo \"Preço\"");
        }

        if (principioAtivo.isBlank()) {
            throw new IllegalArgumentException("Preencha o campo \"Princípio ativo\"");
        }

        if (dosagemMg.isBlank()) {
            throw new IllegalArgumentException("Preencha o campo \"Dosagem\"");
        }

        medicamento.setNome(nome);
        medicamento.setPrincipioAtivo(principioAtivo);

        try {
            medicamento.setDosagemMg(Float.parseFloat(dosagemMg));
        } catch (NumberFormatException nfe) {
            throw new NumberFormatException("O campo \"Dosagem\" precisa ser um número");
        }
        try {
            medicamento.setPreco(Float.parseFloat(preco));
        } catch (NumberFormatException nfe) {
            throw new NumberFormatException("O campo \"Preço\" precisa ser um número");
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cancelarBotao;
    private javax.swing.JTextField dosagemInput;
    private javax.swing.JLabel dosagemLabel;
    private javax.swing.JLabel generoLabel;
    private javax.swing.JComboBox<String> generoSelect;
    private javax.swing.JFormattedTextField jFormattedTextField1;
    private javax.swing.JTextField nomeInput;
    private javax.swing.JLabel nomeLabel;
    private javax.swing.JPanel painelCamposEspecificos;
    private javax.swing.JTextField precoInput;
    private javax.swing.JLabel precoLabel;
    private javax.swing.JLabel pricipioAtivoLabel;
    private javax.swing.JTextField principioAtivoInput;
    private javax.swing.JButton resetarBotao;
    private javax.swing.JButton salvarBotao;
    // End of variables declaration//GEN-END:variables

}
