
import javax.swing.JOptionPane;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
/**
 *
 * @author otavio
 */
public class FormLaboratorio extends javax.swing.JFrame implements FormularioComponente<Laboratorio> {

    private static FormLaboratorio instance;
    private static final java.util.logging.Logger logger = java.util.logging.Logger
            .getLogger(FormLaboratorio.class.getName());

    /**
     * Creates new form FormLaboratorio
     */
    private FormLaboratorio() {
        initComponents();
        limparFormulario();
    }

    // MÉTODO SINGLETON
    public static FormLaboratorio getInstance() {
        if (instance == null) {
            instance = new FormLaboratorio();
        }

        return instance;
    }

    // Sobreescrita
    @Override
    public void setVisible(boolean b) {
        limparFormulario();
        super.setVisible(b);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated
    // Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        nomeLabel = new javax.swing.JLabel();
        nomeInput = new javax.swing.JTextField();
        cnpjLabel = new javax.swing.JLabel();
        cnpjInput = new javax.swing.JTextField();
        enderecoLabel = new javax.swing.JLabel();
        enderecoInput = new javax.swing.JTextField();
        telefoneLabel = new javax.swing.JLabel();
        telefoneInput = new javax.swing.JTextField();
        emailLabel = new javax.swing.JLabel();
        emailInput = new javax.swing.JTextField();
        salvarBotao = new javax.swing.JButton();
        cancelarBotao = new javax.swing.JButton();
        resetarBotao = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        nomeLabel.setText("Nome");

        cnpjLabel.setText("CNPJ");

        cnpjInput.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cnpjInputActionPerformed(evt);
            }
        });

        enderecoLabel.setText("Endereço");

        enderecoInput.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                enderecoInputActionPerformed(evt);
            }
        });

        telefoneLabel.setText("Telefone");

        telefoneInput.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                telefoneInputActionPerformed(evt);
            }
        });

        emailLabel.setText("Email");

        emailInput.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                emailInputActionPerformed(evt);
            }
        });

        salvarBotao.setText("Salvar");
        salvarBotao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                salvarBotaoActionPerformed(evt);
            }
        });

        cancelarBotao.setText("Cancelar");
        cancelarBotao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelarBotaoActionPerformed(evt);
            }
        });

        resetarBotao.setText("Resetar");
        resetarBotao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                resetarBotaoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addGap(20, 20, 20)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addGroup(layout.createSequentialGroup()
                                                .addComponent(resetarBotao)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addComponent(cancelarBotao)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addComponent(salvarBotao))
                                        .addGroup(
                                                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING,
                                                        false)
                                                        .addComponent(enderecoInput)
                                                        .addGroup(layout.createSequentialGroup()
                                                                .addGroup(layout.createParallelGroup(
                                                                        javax.swing.GroupLayout.Alignment.LEADING,
                                                                        false)
                                                                        .addComponent(nomeLabel,
                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                Short.MAX_VALUE)
                                                                        .addComponent(nomeInput,
                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                256, Short.MAX_VALUE)
                                                                        .addComponent(telefoneLabel,
                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                Short.MAX_VALUE))
                                                                .addGap(18, 18, 18)
                                                                .addGroup(layout.createParallelGroup(
                                                                        javax.swing.GroupLayout.Alignment.LEADING)
                                                                        .addComponent(cnpjLabel,
                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                Short.MAX_VALUE)
                                                                        .addComponent(cnpjInput)
                                                                        .addComponent(emailLabel,
                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                Short.MAX_VALUE)))
                                                        .addComponent(enderecoLabel,
                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                        .addGroup(layout.createSequentialGroup()
                                                                .addComponent(telefoneInput,
                                                                        javax.swing.GroupLayout.PREFERRED_SIZE, 256,
                                                                        javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                .addGap(18, 18, 18)
                                                                .addComponent(emailInput,
                                                                        javax.swing.GroupLayout.DEFAULT_SIZE, 256,
                                                                        Short.MAX_VALUE))))
                                .addContainerGap(20, Short.MAX_VALUE)));
        layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addGap(20, 20, 20)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(nomeLabel)
                                        .addComponent(cnpjLabel))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(nomeInput, javax.swing.GroupLayout.PREFERRED_SIZE,
                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(cnpjInput, javax.swing.GroupLayout.PREFERRED_SIZE,
                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addComponent(enderecoLabel)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(enderecoInput, javax.swing.GroupLayout.PREFERRED_SIZE,
                                        javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(telefoneLabel)
                                        .addComponent(emailLabel))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(telefoneInput, javax.swing.GroupLayout.PREFERRED_SIZE,
                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(emailInput, javax.swing.GroupLayout.PREFERRED_SIZE,
                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 44,
                                        Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(salvarBotao)
                                        .addComponent(cancelarBotao)
                                        .addComponent(resetarBotao))
                                .addContainerGap()));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cnpjInputActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_cnpjInputActionPerformed
        // TODO add your handling code here:
    }// GEN-LAST:event_cnpjInputActionPerformed

    private void enderecoInputActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_enderecoInputActionPerformed
        // TODO add your handling code here:
    }// GEN-LAST:event_enderecoInputActionPerformed

    private void emailInputActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_emailInputActionPerformed
        // TODO add your handling code here:
    }// GEN-LAST:event_emailInputActionPerformed

    private void telefoneInputActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_telefoneInputActionPerformed
        // TODO add your handling code here:
    }// GEN-LAST:event_telefoneInputActionPerformed

    private void salvarBotaoActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_salvarBotaoActionPerformed
        Laboratorio laboratorio = new Laboratorio();

        try {
            this.setarDados(laboratorio);

            BDLaboratorio.getInstance().addLaboratorio(laboratorio);

            this.limparFormulario();
            this.dispose();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(
                    this,
                    e.getMessage(),
                    "Erro " + e.getClass().getName(),
                    JOptionPane.ERROR_MESSAGE);
        }
    }// GEN-LAST:event_salvarBotaoActionPerformed

    private void cancelarBotaoActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_cancelarBotaoActionPerformed
        this.dispose();
    }// GEN-LAST:event_cancelarBotaoActionPerformed

    private void resetarBotaoActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_resetarBotaoActionPerformed
        this.limparFormulario();
    }// GEN-LAST:event_resetarBotaoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        // <editor-fold defaultstate="collapsed" desc=" Look and feel setting code
        // (optional) ">
        /*
         * If Nimbus (introduced in Java SE 6) is not available, stay with the default
         * look and feel.
         * For details see
         * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        // </editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new FormLaboratorio().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cancelarBotao;
    private javax.swing.JTextField cnpjInput;
    private javax.swing.JLabel cnpjLabel;
    private javax.swing.JTextField emailInput;
    private javax.swing.JLabel emailLabel;
    private javax.swing.JTextField enderecoInput;
    private javax.swing.JLabel enderecoLabel;
    private javax.swing.JTextField nomeInput;
    private javax.swing.JLabel nomeLabel;
    private javax.swing.JButton resetarBotao;
    private javax.swing.JButton salvarBotao;
    private javax.swing.JTextField telefoneInput;
    private javax.swing.JLabel telefoneLabel;
    // End of variables declaration//GEN-END:variables

    @Override
    public final void limparFormulario() {
        this.nomeInput.setText("");
        this.cnpjInput.setText("");
        this.enderecoInput.setText("");
        this.telefoneInput.setText("");
        this.emailInput.setText("");

        this.repaint();
        this.revalidate();
    }

    @Override
    public void setarDados(Laboratorio laboratorio) throws IllegalArgumentException {
        String nome = this.nomeInput.getText();
        String cnpj = this.cnpjInput.getText();
        String endereco = this.enderecoInput.getText();
        String telefone = this.telefoneInput.getText();
        String email = this.emailInput.getText();

        if (nome.isBlank()) {
            throw new IllegalArgumentException("Preencha o campo \"Nome\"");
        }

        if (cnpj.isBlank()) {
            throw new IllegalArgumentException("Preencha o campo \"CNPJ\"");
        }

        if (endereco.isBlank()) {
            throw new IllegalArgumentException("Preencha o campo \"Endereço\"");
        }

        if (telefone.isBlank()) {
            throw new IllegalArgumentException("Preencha o campo \"Telefone\"");
        }

        if (email.isBlank()) {
            throw new IllegalArgumentException("Preencha o campo \"Email\"");
        }

        laboratorio.setNome(nome);
        laboratorio.setCnpj(cnpj);
        laboratorio.setEndereco(endereco);
        laboratorio.setTelefone(telefone);
        laboratorio.setEmail(email);
    }

    @Override
    public void preencherForm(Laboratorio laboratorio) {
        this.nomeInput.setText(laboratorio.getNome());
        this.cnpjInput.setText(laboratorio.getCnpj());
        this.enderecoInput.setText(laboratorio.getEndereco());
        this.telefoneInput.setText(laboratorio.getTelefone());
        this.emailInput.setText(laboratorio.getEmail());

        this.repaint();
        this.revalidate();
    }
}
