// Apache NetBeans IDE 26
// Otavio Luiz Gonzaga - RA: a2648920

import java.util.List;
import java.util.Collections;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author otavio
 */
public class FormPrincipal extends javax.swing.JFrame {
    private List<Medicamento> medicamentos;
    private List<Laboratorio> laboratorios;
    private static final java.util.logging.Logger logger = java.util.logging.Logger
            .getLogger(FormPrincipal.class.getName());

    /**
     * Creates new form Principal
     */
    public FormPrincipal() {
        this.medicamentos = Collections.emptyList();
        this.laboratorios = Collections.emptyList();
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated
    // Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuItem1 = new javax.swing.JMenuItem();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        barraDeMenu = new javax.swing.JMenuBar();
        MenuMedicamento = new javax.swing.JMenu();
        cadastrarMedicamentoItem = new javax.swing.JMenuItem();
        abrirListagemMedicamentoItem = new javax.swing.JMenuItem();

        jMenuItem1.setText("jMenuItem1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Gerenciador de Medicamentos");

        jLabel1.setForeground(new java.awt.Color(102, 102, 102));
        jLabel1.setText("Cadastrar medicamento");

        jLabel2.setText("Ctrl + N");

        jLabel3.setForeground(new java.awt.Color(102, 102, 102));
        jLabel3.setText("Visualizar medicamentos");

        jLabel4.setText("Ctrl + M");

        MenuMedicamento.setText("Medicamento");

        cadastrarMedicamentoItem.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_N,
                java.awt.event.InputEvent.CTRL_DOWN_MASK));
        cadastrarMedicamentoItem.setText("Cadastrar");
        cadastrarMedicamentoItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cadastrarMedicamentoItemActionPerformed(evt);
            }
        });
        MenuMedicamento.add(cadastrarMedicamentoItem);

        abrirListagemMedicamentoItem.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_M,
                java.awt.event.InputEvent.CTRL_DOWN_MASK));
        abrirListagemMedicamentoItem.setText("Abrir listagem");
        abrirListagemMedicamentoItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                abrirListagemMedicamentoItemActionPerformed(evt);
            }
        });
        MenuMedicamento.add(abrirListagemMedicamentoItem);

        barraDeMenu.add(MenuMedicamento);

        setJMenuBar(barraDeMenu);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addGap(82, 82, 82)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(jLabel1)
                                        .addComponent(jLabel3))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel4)
                                        .addComponent(jLabel2))
                                .addContainerGap(220, Short.MAX_VALUE)));
        layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addGap(114, 114, 114)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jLabel1)
                                        .addComponent(jLabel2))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jLabel4)
                                        .addComponent(jLabel3))
                                .addContainerGap(192, Short.MAX_VALUE)));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cadastrarMedicamentoItemActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_cadastrarMedicamentoItemActionPerformed
        FormMedicamento.getInstance().setVisible(true);
    }// GEN-LAST:event_cadastrarMedicamentoItemActionPerformed

    private void abrirListagemMedicamentoItemActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_abrirListagemMedicamentoItemActionPerformed
        ListagemMedicamento.getInstance().setVisible(true);
    }// GEN-LAST:event_abrirListagemMedicamentoItemActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        // <editor-fold defaultstate="collapsed" desc=" Look and feel setting code
        // (optional) ">
        /*
         * If Nimbus (introduced in Java SE 6) is not available, stay with the default
         * look and feel.
         * For details see
         * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        // </editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new FormPrincipal().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu MenuMedicamento;
    private javax.swing.JMenuItem abrirListagemMedicamentoItem;
    private javax.swing.JMenuBar barraDeMenu;
    private javax.swing.JMenuItem cadastrarMedicamentoItem;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JMenuItem jMenuItem1;
    // End of variables declaration//GEN-END:variables
}
