// Otavio Luiz Gonzaga - RA: a2648920

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */

/**
 *
 * @author otavio
 */
public class FormComum extends javax.swing.JPanel implements FormularioComponente<Comum> {

    /**
     * Creates new form ComumFormulario
     */
    public FormComum() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        receitaLabel = new javax.swing.JLabel();
        receitaCheckbox = new javax.swing.JCheckBox();
        viaAdministracaoLabel = new javax.swing.JLabel();
        viaAdministracaoInput = new javax.swing.JTextField();

        receitaLabel.setText("Receita?");

        receitaCheckbox.setText("Vendido sem receita");
        receitaCheckbox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                receitaCheckboxActionPerformed(evt);
            }
        });

        viaAdministracaoLabel.setText("Via de administração");

        viaAdministracaoInput.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viaAdministracaoInputActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(receitaCheckbox, javax.swing.GroupLayout.DEFAULT_SIZE, 256, Short.MAX_VALUE)
                    .addComponent(receitaLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(viaAdministracaoInput)
                    .addComponent(viaAdministracaoLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 256, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(receitaLabel)
                    .addComponent(viaAdministracaoLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(receitaCheckbox)
                    .addComponent(viaAdministracaoInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void receitaCheckboxActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_receitaCheckboxActionPerformed
        // TODO add your handling code here:
    }// GEN-LAST:event_receitaCheckboxActionPerformed

    private void viaAdministracaoInputActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_viaAdministracaoInputActionPerformed
        // TODO add your handling code here:
    }// GEN-LAST:event_viaAdministracaoInputActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox receitaCheckbox;
    private javax.swing.JLabel receitaLabel;
    private javax.swing.JTextField viaAdministracaoInput;
    private javax.swing.JLabel viaAdministracaoLabel;
    // End of variables declaration//GEN-END:variables

    @Override
    public void limparFormulario() {
        this.receitaCheckbox.setSelected(false);
        this.receitaCheckbox.repaint();
        this.receitaCheckbox.revalidate();

        this.viaAdministracaoInput.setText("");
        this.viaAdministracaoInput.repaint();
        this.viaAdministracaoInput.revalidate();

        this.repaint();
        this.revalidate();

    }

    @Override
    public void setarDados(Comum comum) throws IllegalArgumentException {
        if (this.viaAdministracaoInput.getText().isBlank()) {
            throw new IllegalArgumentException("Preencha o campo \"Via de administração\"");
        }

        comum.setVendidoSemReceita(this.receitaCheckbox.isSelected());
        comum.setViaAdministracao(this.viaAdministracaoInput.getText());
    }

    @Override
    public void preencherForm(Comum medicamento) {
        this.receitaCheckbox.setSelected(medicamento.getVendidoSemReceita());
        this.viaAdministracaoInput.setText(medicamento.getViaAdministracao());
        
        this.repaint();
        this.revalidate();
    }
}
