// Otavio Luiz Gonzaga - RA: a2648920

import javax.swing.JOptionPane;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
/**
 *
 * @author otavio
 */

public class ListagemMedicamento extends javax.swing.JFrame {

    private static ListagemMedicamento instance;
    private static final java.util.logging.Logger logger = java.util.logging.Logger
            .getLogger(ListagemMedicamento.class.getName());

    /**
     * Creates new form ListagemMedicamento
     */
    private ListagemMedicamento() {
        initComponents();

        MedicamentoTableModel model = new MedicamentoTableModel();
        this.medicamentoTable.setModel(model);
    }

    public static ListagemMedicamento getInstance() {
        if (instance == null) {
            instance = new ListagemMedicamento();
        }

        return instance;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated
    // Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        medicamentoTable = new javax.swing.JTable();
        h1 = new javax.swing.JLabel();
        deletarBotao = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        medicamentoTable.setModel(new javax.swing.table.DefaultTableModel(
                new Object[][] {

                },
                new String[] {
                        "Nome", "Preço", "Principio ativo", "Dosagem", "Gênero"
                }) {
            Class[] types = new Class[] {
                    java.lang.String.class, java.lang.Float.class, java.lang.Float.class, java.lang.Float.class,
                    java.lang.String.class
            };
            boolean[] canEdit = new boolean[] {
                    false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types[columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit[columnIndex];
            }
        });
        medicamentoTable.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                medicamentoTableComponentShown(evt);
            }
        });
        jScrollPane1.setViewportView(medicamentoTable);
        if (medicamentoTable.getColumnModel().getColumnCount() > 0) {
            medicamentoTable.getColumnModel().getColumn(2).setMinWidth(180);
        }

        h1.setFont(new java.awt.Font("sansserif", 0, 24)); // NOI18N
        h1.setText("Medicamentos");

        deletarBotao.setText("Deletar");
        deletarBotao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deletarBotaoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING,
                                                layout.createSequentialGroup()
                                                        .addGap(0, 0, Short.MAX_VALUE)
                                                        .addComponent(jScrollPane1,
                                                                javax.swing.GroupLayout.PREFERRED_SIZE, 535,
                                                                javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(layout.createSequentialGroup()
                                                .addComponent(h1)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED,
                                                        javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(deletarBotao)))
                                .addContainerGap()));
        layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addGap(21, 21, 21)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(h1)
                                        .addComponent(deletarBotao))
                                .addGap(18, 18, 18)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 262, Short.MAX_VALUE)
                                .addContainerGap()));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void medicamentoTableComponentShown(java.awt.event.ComponentEvent evt) {// GEN-FIRST:event_medicamentoTableComponentShown
        // TODO add your handling code here:
    }// GEN-LAST:event_medicamentoTableComponentShown

    private void deletarBotaoActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_deletarBotaoActionPerformed
        int linhaSelecionada = medicamentoTable.getSelectedRow();
        if (linhaSelecionada == -1) {
            JOptionPane.showMessageDialog(this, "Selecione uma linha para remover.", "Aviso",
                    JOptionPane.WARNING_MESSAGE);
            return;
        }

        int confirm = JOptionPane.showConfirmDialog(this, "Confirma a remoção do medicamento selecionado?",
                "Confirmação", JOptionPane.YES_NO_OPTION);
        if (confirm != JOptionPane.YES_OPTION) {
            return;
        }

        MedicamentoTableModel tableModel = ((MedicamentoTableModel) this.medicamentoTable.getModel());

        tableModel.removerLinha(linhaSelecionada);
    }// GEN-LAST:event_deletarBotaoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        // <editor-fold defaultstate="collapsed" desc=" Look and feel setting code
        // (optional) ">
        /*
         * If Nimbus (introduced in Java SE 6) is not available, stay with the default
         * look and feel.
         * For details see
         * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        // </editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new ListagemMedicamento().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton deletarBotao;
    private javax.swing.JLabel h1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable medicamentoTable;
    // End of variables declaration//GEN-END:variables
}
