// Otavio Luiz Gonzaga - RA: a2648920

import javax.swing.JOptionPane;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
/**
 *
 * @author otavio
 */
public class ListagemLaboratorio extends javax.swing.JFrame {

    private static ListagemLaboratorio instance;
    private static final java.util.logging.Logger logger = java.util.logging.Logger
            .getLogger(ListagemLaboratorio.class.getName());

    /**
     * Creates new form ListagemLaboratorio
     */
    private ListagemLaboratorio() {
        initComponents();

        LaboratorioTableModel model = new LaboratorioTableModel();
        this.laboratorioTabela.setModel(model);
    }

    // MÉTODO SINGLETON
    public static ListagemLaboratorio getInstance() {
        if (instance == null) {
            instance = new ListagemLaboratorio();
        }

        return instance;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jProgressBar1 = new javax.swing.JProgressBar();
        jScrollPane1 = new javax.swing.JScrollPane();
        laboratorioTabela = new javax.swing.JTable();
        tituloLabel = new javax.swing.JLabel();
        editarInfoLabel = new javax.swing.JLabel();
        deletarBotao = new javax.swing.JButton();
        detalhesBotao = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        laboratorioTabela.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(laboratorioTabela);

        tituloLabel.setFont(new java.awt.Font("sansserif", 0, 24)); // NOI18N
        tituloLabel.setText("Laboratórios");

        editarInfoLabel.setFont(new java.awt.Font("sansserif", 0, 14)); // NOI18N
        editarInfoLabel.setForeground(new java.awt.Color(102, 102, 102));
        editarInfoLabel.setText("Para editar um valor, clique sobre a célula");

        deletarBotao.setText("Deletar");
        deletarBotao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deletarBotaoActionPerformed(evt);
            }
        });

        detalhesBotao.setText("Detalhes");
        detalhesBotao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                detalhesBotaoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 638, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(editarInfoLabel)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(tituloLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(detalhesBotao)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(deletarBotao)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addComponent(tituloLabel))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(deletarBotao)
                            .addComponent(detalhesBotao))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(editarInfoLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void detalhesBotaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_detalhesBotaoActionPerformed
        int selectedRow = laboratorioTabela.getSelectedRow();

        if (selectedRow == -1) {
            JOptionPane.showMessageDialog(this, "Selecione uma linha para visualizar os detalhes.");
            return;
        }

        LaboratorioTableModel model = (LaboratorioTableModel) laboratorioTabela.getModel();
        Laboratorio l = model.getLaboratorio(selectedRow);

        FormLaboratorio form = FormLaboratorio.getInstance();
        form.setVisible(true);
        form.preencherForm(l);
    }//GEN-LAST:event_detalhesBotaoActionPerformed

    private void deletarBotaoActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_deletarBotaoActionPerformed
        int linhaSelecionada = laboratorioTabela.getSelectedRow();
        if (linhaSelecionada == -1) {
            JOptionPane.showMessageDialog(this, "Selecione uma linha para remover.", "Aviso",
                    JOptionPane.WARNING_MESSAGE);
            return;
        }

        int confirm = JOptionPane.showConfirmDialog(this, "Confirma a remoção do laboratório selecionado?",
                "Confirmação", JOptionPane.YES_NO_OPTION);
        if (confirm != JOptionPane.YES_OPTION) {
            return;
        }

        LaboratorioTableModel tableModel = ((LaboratorioTableModel) this.laboratorioTabela.getModel());

        tableModel.removerLinha(linhaSelecionada);
    }// GEN-LAST:event_deletarBotaoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        // <editor-fold defaultstate="collapsed" desc=" Look and feel setting code
        // (optional) ">
        /*
         * If Nimbus (introduced in Java SE 6) is not available, stay with the default
         * look and feel.
         * For details see
         * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        // </editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new ListagemLaboratorio().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton deletarBotao;
    private javax.swing.JButton detalhesBotao;
    private javax.swing.JLabel editarInfoLabel;
    private javax.swing.JProgressBar jProgressBar1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable laboratorioTabela;
    private javax.swing.JLabel tituloLabel;
    // End of variables declaration//GEN-END:variables
}
